# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Usman Anwar
tagline:             'Another ML blog.'
description:         'I am a senior in Electrical Engineering. I blog about Machine Learning and Intelligent Machines.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Usman Anwar
  url:               https://twitter.com/rantistan
  email:             usmananwar391@gmail.com
