# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Usman Anwar
tagline:             'Another ML blog.'
description:         'I am a machine learning researcher at Information Technology University Lahore working with Dr. Ali Ahmed. I blog about Machine Learning and Intelligent Machines.'
url:                 uzman-anwar.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Usman Anwar
  url:               https://twitter.com/rantistan
  email:             usmananwar391@gmail.com

# Plugins
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
