# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:               Usman Anwar
tagline:             'Another ML blog.'
description: 'I am a senior in Electrical Engineering. I blog about Machine Learning and Intelligent Machines.'
url:              http://lanyon.getpoole.com

author:
  name:              Usman Anwar
  url:               https://twitter.com/rantistan
  email: usmananwar391@gmail.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
